/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnp;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author SWAPNIL LAHOTI
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    private static final long serialVersionUID = 1L;
	int x=0, y=100;
	
	public void paint(Graphics g)
	{
		super.paint(g);
		Graphics2D g2 = (Graphics2D)g;
		Font font = new Font("Courier", Font.BOLD,20);
		g2.setFont(font);
		g2.setColor(Color.RED);
		g2.drawString("CONGRATULAIONS!!! To our 234 students placed in 2017-18 , with average 6 CTC ", x, y);
		
		
		try{Thread.sleep(10);}catch (Exception e) {}
			// TODO: handle exception
			x++;
			if(x>this.getWidth())
			{
				x=0;
			}
			repaint();
		}
        
        
        
        
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 445));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/Picture27.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(110, 150, 140, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/TCS.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(320, 170, 160, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/infosys.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(530, 180, 170, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/Picture28.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel5);
        jLabel5.setBounds(180, 350, 160, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/Picture29.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(460, 300, 140, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/Webp.net-resizeimage (10).jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 450);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
