/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnp;

import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SWAPNIL LAHOTI
 */
public class StudentLogin extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogin
     */
    stu_panel p1;
    public StudentLogin() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rollTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        branchTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobiTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aggrTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deadTxt = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        liveTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(920, 470));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Live Backlogs :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(95, 379, 98, 17);
        jPanel1.add(rollTxt);
        rollTxt.setBounds(252, 156, 279, 37);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Student");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(352, 11, 201, 24);

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nameTxt);
        nameTxt.setBounds(252, 196, 279, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student profile");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(383, 91, 131, 22);

        branchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchTxtActionPerformed(evt);
            }
        });
        jPanel1.add(branchTxt);
        branchTxt.setBounds(252, 234, 279, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter Your Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(95, 128, 161, 22);
        jPanel1.add(mobiTxt);
        mobiTxt.setBounds(252, 272, 279, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Roll No :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(95, 156, 98, 17);
        jPanel1.add(aggrTxt);
        aggrTxt.setBounds(252, 315, 279, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Full Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(95, 196, 98, 17);
        jPanel1.add(deadTxt);
        deadTxt.setBounds(252, 353, 279, 37);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(550, 400, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Branch :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(95, 234, 98, 17);
        jPanel1.add(liveTxt);
        liveTxt.setBounds(252, 379, 279, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mobile No :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(95, 272, 98, 17);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(340, 410, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Aggregate :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(95, 315, 98, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dead Backlogs :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(95, 353, 115, 17);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView);
        btnView.setBounds(659, 72, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Companies you are eligible for ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(610, 37, 222, 17);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(569, 128, 290, 207);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnp/Webp.net-resizeimage (10).jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 920, 445);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 1, 900, 470);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void branchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchTxtActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try{
					Class.forName("com.mysql.cj.jdbc.Driver");
					Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tnp1","root","");
				Statement st = con.createStatement();
			//  preparedStatement st= null;
				String sql = "insert into profile(roll,name,branch,mobi,aggr,dead,live) values ('"+rollTxt.getText()+"','"+nameTxt.getText()+"','"+branchTxt.getText()+"','"+mobiTxt.getText()+"','"+aggrTxt.getText()+"','"+deadTxt.getText()+"','"+liveTxt.getText()+"')";	
			//	st=con.prepareStatement(sql);
			//	st.setString(1, name);
			//	st.setString(2, roll);
				st.executeUpdate(sql);
					//showstuds obj=new showstuds();
					//obj.
					JOptionPane.showMessageDialog(null,"Thank You,Data is successfully Submitted." );
					 sucess_login f2;
        f2 = new sucess_login();
					st.close();
					con.close();
				}
				catch(Exception e)
				{System.out.println(e);}
        
       
        //JOptionPane.showMessageDialog(f2,"Data sucessfully entered");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
try{
					Class.forName("com.mysql.cj.jdbc.Driver");
					Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tnp1","root","");
				
					String query="select cmp_name from company left join profile on company.min_ptr<=profile.aggr && company.dead>=profile.dead && company.live<=profile.live where roll='"+rollTxt.getText()+"'";
					PreparedStatement pst=con.prepareStatement(query);
					ResultSet rs=pst.executeQuery();
					table.setModel(DbUtils.resultSetToTableModel(rs));
					
				
				//st.executeUpdate(sql);
					
					//JOptionPane.showMessageDialog(null,"Data is successfully inserted into the database." );
					//this.;
					pst.close();
					con.close();
				}
				catch(Exception e)
				{System.out.println(e);}       
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
try{
					Class.forName("com.mysql.cj.jdbc.Driver");
					Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tnp1","root","");
					Statement st = con.createStatement();
					
					String query2="update profile set roll='"+rollTxt.getText()+"',name='"+nameTxt.getText()+"',branch='"+branchTxt.getText()+"',mobi='"+mobiTxt.getText()+"',aggr='"+aggrTxt.getText()+"',dead='"+deadTxt.getText()+"',live='"+liveTxt.getText()+"' where roll='"+rollTxt.getText()+"'";
					//PreparedStatement pst=con.prepareStatement(query2);
					//ResultSet rs=pst.executeQuery();
					//table_1.setModel(DbUtils.resultSetToTableModel(rs));
					st.executeUpdate(query2);
				
					JOptionPane.showMessageDialog(null,"Thank You,Data is successfully Updated." );

					con.close();
				}
				catch(Exception e)
				{System.out.println(e);}	
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aggrTxt;
    private javax.swing.JTextField branchTxt;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField deadTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField liveTxt;
    private javax.swing.JTextField mobiTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField rollTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
